name: Asan Check

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  mem_test:
    strategy:
      fail-fast: false
      matrix:
        # ref: https://github.com/actions/runner-images
        os: [ubuntu-latest, macos-15]
        luaVersion: ["5.5.0-beta", "5.4.8"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      # https://www.lua.org/work/lua-5.5.0-beta.tar.gz
      - name: install lua
        run: |
          wget http://www.lua.org/ftp/lua-${{ matrix.luaVersion }}.tar.gz
          tar -xzvf lua-${{ matrix.luaVersion }}.tar.gz
          cd lua-${{ matrix.luaVersion }}
          sudo make
          sudo make install
          sudo cp src/*.h /usr/local/include/
      - name: run asan check
        run: |
          bash .github/asan_assets/test_mem.sh
